version: '3'
services:
  db-mysql:
    container_name: db-mysql
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_DATABASE=helios
      - MYSQL_ROOT_PASSWORD=Helios123
      - MYSQL_ROOT_HOST=%
    ports:
     - "3306:3306"
    restart: always
  webapp-1:
    container_name: webapp-1
    build: ./webapp
    working_dir: /webapp
    volumes:
      - ./webapp:/webapp
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: ["bash", "/webapp/wait-for-it.sh", "db-mysql:3306", "--", "mvn", "clean", "--", "spring-boot:run"]
    depends_on:
      - db-mysql
    restart: always
